name: Push Docker image

on:
  push:
    branches: [ release ]
  schedule:
    # Run at 6:41 UTC on Thursday
    - cron: '41 6 * * 4'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push latest Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build grist-omnibus for testing
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
          pull: true
          load: true
          tags: ${{ github.repository_owner }}/grist-omnibus:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Do a smoke test on grist-omnibus
        run: make test
      - name: Push grist-omnibus to Docker Hub
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ github.repository_owner }}/grist-omnibus:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Push grist-ee-omnibus to Docker Hub
        uses: docker/build-push-action@v2
        with: 
          build-args: |
            BASE=gristlabs/grist-ee:latest
          platforms: linux/amd64,linux/arm64/v8
          pull: true
          push: true
          tags: ${{ github.repository_owner }}/grist-ee-omnibus:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
